// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lcm.sql

package db

import (
	"context"
	"database/sql"
)

const lCMAppendContextItem = `-- name: LCMAppendContextItem :exec
INSERT INTO lcm_context_items (session_id, position, item_type, message_id, summary_id)
SELECT ?, COALESCE(MAX(ci.position), -1) + 1, ?, ?, ?
FROM lcm_context_items ci
WHERE ci.session_id = ?5
`

type LCMAppendContextItemParams struct {
	SessionID string         `json:"session_id"`
	ItemType  string         `json:"item_type"`
	MessageID sql.NullString `json:"message_id"`
	SummaryID sql.NullString `json:"summary_id"`
}

func (q *Queries) LCMAppendContextItem(ctx context.Context, arg LCMAppendContextItemParams) error {
	_, err := q.exec(ctx, q.lCMAppendContextItemStmt, lCMAppendContextItem,
		arg.SessionID,
		arg.ItemType,
		arg.MessageID,
		arg.SummaryID,
		arg.SessionID,
	)
	return err
}

const lCMCountMessagesInContext = `-- name: LCMCountMessagesInContext :one
SELECT COUNT(*) FROM lcm_context_items
WHERE session_id = ? AND item_type = 'message'
`

func (q *Queries) LCMCountMessagesInContext(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.lCMCountMessagesInContextStmt, lCMCountMessagesInContext, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const lCMCountSummariesInContext = `-- name: LCMCountSummariesInContext :one
SELECT COUNT(*) FROM lcm_context_items
WHERE session_id = ? AND item_type = 'summary'
`

func (q *Queries) LCMCountSummariesInContext(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.lCMCountSummariesInContextStmt, lCMCountSummariesInContext, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const lCMExpandSummaryToMessages = `-- name: LCMExpandSummaryToMessages :many
SELECT m.id, m.session_id, m.role, m.parts AS content, m.created_at
FROM lcm_summary_messages sm
JOIN messages m ON m.id = sm.message_id
WHERE sm.summary_id = ?
ORDER BY sm.ord
`

type LCMExpandSummaryToMessagesRow struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Role      string `json:"role"`
	Content   string `json:"content"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) LCMExpandSummaryToMessages(ctx context.Context, summaryID string) ([]LCMExpandSummaryToMessagesRow, error) {
	rows, err := q.query(ctx, q.lCMExpandSummaryToMessagesStmt, lCMExpandSummaryToMessages, summaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LCMExpandSummaryToMessagesRow{}
	for rows.Next() {
		var i LCMExpandSummaryToMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lCMGetContextTokenCount = `-- name: LCMGetContextTokenCount :one
SELECT COALESCE(SUM(
    CASE
        WHEN ci.item_type = 'message' THEN LENGTH(COALESCE(m.parts, '')) / 4
        WHEN ci.item_type = 'summary' THEN s.token_count
        ELSE 0
    END
), 0) AS total_tokens
FROM lcm_context_items ci
LEFT JOIN messages m ON m.id = ci.message_id
LEFT JOIN lcm_summaries s ON s.summary_id = ci.summary_id
WHERE ci.session_id = ?
`

func (q *Queries) LCMGetContextTokenCount(ctx context.Context, sessionID string) (interface{}, error) {
	row := q.queryRow(ctx, q.lCMGetContextTokenCountStmt, lCMGetContextTokenCount, sessionID)
	var total_tokens interface{}
	err := row.Scan(&total_tokens)
	return total_tokens, err
}

const lCMGetCurrentContext = `-- name: LCMGetCurrentContext :many
SELECT
    ci.position,
    ci.item_type,
    ci.message_id,
    ci.summary_id,
    COALESCE(m.role, 'summary') AS role,
    COALESCE(m.parts, s.content) AS content,
    CASE
        WHEN ci.item_type = 'message' THEN LENGTH(COALESCE(m.parts, '')) / 4
        ELSE COALESCE(s.token_count, 0)
    END AS token_count,
    COALESCE(s.kind, '') AS summary_kind
FROM lcm_context_items ci
LEFT JOIN messages m ON m.id = ci.message_id
LEFT JOIN lcm_summaries s ON s.summary_id = ci.summary_id
WHERE ci.session_id = ?
ORDER BY ci.position
`

type LCMGetCurrentContextRow struct {
	Position    int64          `json:"position"`
	ItemType    string         `json:"item_type"`
	MessageID   sql.NullString `json:"message_id"`
	SummaryID   sql.NullString `json:"summary_id"`
	Role        string         `json:"role"`
	Content     string         `json:"content"`
	TokenCount  interface{}    `json:"token_count"`
	SummaryKind string         `json:"summary_kind"`
}

func (q *Queries) LCMGetCurrentContext(ctx context.Context, sessionID string) ([]LCMGetCurrentContextRow, error) {
	rows, err := q.query(ctx, q.lCMGetCurrentContextStmt, lCMGetCurrentContext, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LCMGetCurrentContextRow{}
	for rows.Next() {
		var i LCMGetCurrentContextRow
		if err := rows.Scan(
			&i.Position,
			&i.ItemType,
			&i.MessageID,
			&i.SummaryID,
			&i.Role,
			&i.Content,
			&i.TokenCount,
			&i.SummaryKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lCMGetLargeFile = `-- name: LCMGetLargeFile :one
SELECT file_id, session_id, original_path, mime_type, token_count, created_at
FROM lcm_large_files WHERE file_id = ?
`

func (q *Queries) LCMGetLargeFile(ctx context.Context, fileID string) (LcmLargeFile, error) {
	row := q.queryRow(ctx, q.lCMGetLargeFileStmt, lCMGetLargeFile, fileID)
	var i LcmLargeFile
	err := row.Scan(
		&i.FileID,
		&i.SessionID,
		&i.OriginalPath,
		&i.MimeType,
		&i.TokenCount,
		&i.CreatedAt,
	)
	return i, err
}

const lCMGetMessageByID = `-- name: LCMGetMessageByID :one
SELECT m.id, m.session_id, m.role, m.parts AS content, m.created_at
FROM messages m
WHERE m.id = ?
`

type LCMGetMessageByIDRow struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Role      string `json:"role"`
	Content   string `json:"content"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) LCMGetMessageByID(ctx context.Context, id string) (LCMGetMessageByIDRow, error) {
	row := q.queryRow(ctx, q.lCMGetMessageByIDStmt, lCMGetMessageByID, id)
	var i LCMGetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const lCMGetMessagesToSummarize = `-- name: LCMGetMessagesToSummarize :many
SELECT ci.position, ci.item_type, ci.message_id, ci.summary_id
FROM lcm_context_items ci
WHERE ci.session_id = ? AND ci.item_type = 'message'
ORDER BY ci.position
LIMIT ?
`

type LCMGetMessagesToSummarizeParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

type LCMGetMessagesToSummarizeRow struct {
	Position  int64          `json:"position"`
	ItemType  string         `json:"item_type"`
	MessageID sql.NullString `json:"message_id"`
	SummaryID sql.NullString `json:"summary_id"`
}

func (q *Queries) LCMGetMessagesToSummarize(ctx context.Context, arg LCMGetMessagesToSummarizeParams) ([]LCMGetMessagesToSummarizeRow, error) {
	rows, err := q.query(ctx, q.lCMGetMessagesToSummarizeStmt, lCMGetMessagesToSummarize, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LCMGetMessagesToSummarizeRow{}
	for rows.Next() {
		var i LCMGetMessagesToSummarizeRow
		if err := rows.Scan(
			&i.Position,
			&i.ItemType,
			&i.MessageID,
			&i.SummaryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lCMGetOldestSummariesInContext = `-- name: LCMGetOldestSummariesInContext :many
SELECT ci.position, ci.item_type, ci.message_id, ci.summary_id
FROM lcm_context_items ci
WHERE ci.session_id = ? AND ci.item_type = 'summary'
ORDER BY ci.position
LIMIT ?
`

type LCMGetOldestSummariesInContextParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

type LCMGetOldestSummariesInContextRow struct {
	Position  int64          `json:"position"`
	ItemType  string         `json:"item_type"`
	MessageID sql.NullString `json:"message_id"`
	SummaryID sql.NullString `json:"summary_id"`
}

func (q *Queries) LCMGetOldestSummariesInContext(ctx context.Context, arg LCMGetOldestSummariesInContextParams) ([]LCMGetOldestSummariesInContextRow, error) {
	rows, err := q.query(ctx, q.lCMGetOldestSummariesInContextStmt, lCMGetOldestSummariesInContext, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LCMGetOldestSummariesInContextRow{}
	for rows.Next() {
		var i LCMGetOldestSummariesInContextRow
		if err := rows.Scan(
			&i.Position,
			&i.ItemType,
			&i.MessageID,
			&i.SummaryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lCMGetSummaryByID = `-- name: LCMGetSummaryByID :one
SELECT summary_id, session_id, kind, content, token_count, file_ids, created_at
FROM lcm_summaries WHERE summary_id = ?
`

type LCMGetSummaryByIDRow struct {
	SummaryID  string `json:"summary_id"`
	SessionID  string `json:"session_id"`
	Kind       string `json:"kind"`
	Content    string `json:"content"`
	TokenCount int64  `json:"token_count"`
	FileIds    string `json:"file_ids"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) LCMGetSummaryByID(ctx context.Context, summaryID string) (LCMGetSummaryByIDRow, error) {
	row := q.queryRow(ctx, q.lCMGetSummaryByIDStmt, lCMGetSummaryByID, summaryID)
	var i LCMGetSummaryByIDRow
	err := row.Scan(
		&i.SummaryID,
		&i.SessionID,
		&i.Kind,
		&i.Content,
		&i.TokenCount,
		&i.FileIds,
		&i.CreatedAt,
	)
	return i, err
}

const lCMGetSummaryParentIDs = `-- name: LCMGetSummaryParentIDs :many
SELECT parent_summary_id FROM lcm_summary_parents
WHERE summary_id = ? ORDER BY ord
`

func (q *Queries) LCMGetSummaryParentIDs(ctx context.Context, summaryID string) ([]string, error) {
	rows, err := q.query(ctx, q.lCMGetSummaryParentIDsStmt, lCMGetSummaryParentIDs, summaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var parent_summary_id string
		if err := rows.Scan(&parent_summary_id); err != nil {
			return nil, err
		}
		items = append(items, parent_summary_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lCMInsertLargeFile = `-- name: LCMInsertLargeFile :exec

INSERT INTO lcm_large_files (file_id, session_id, original_path, mime_type, token_count)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(file_id) DO NOTHING
`

type LCMInsertLargeFileParams struct {
	FileID       string `json:"file_id"`
	SessionID    string `json:"session_id"`
	OriginalPath string `json:"original_path"`
	MimeType     string `json:"mime_type"`
	TokenCount   int64  `json:"token_count"`
}

// FTS5 search query is implemented directly in the SQLiteStore
// because sqlc cannot introspect FTS5 virtual tables.
func (q *Queries) LCMInsertLargeFile(ctx context.Context, arg LCMInsertLargeFileParams) error {
	_, err := q.exec(ctx, q.lCMInsertLargeFileStmt, lCMInsertLargeFile,
		arg.FileID,
		arg.SessionID,
		arg.OriginalPath,
		arg.MimeType,
		arg.TokenCount,
	)
	return err
}

const lCMInsertSummary = `-- name: LCMInsertSummary :exec
INSERT INTO lcm_summaries (summary_id, session_id, kind, content, token_count, file_ids)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(summary_id) DO NOTHING
`

type LCMInsertSummaryParams struct {
	SummaryID  string `json:"summary_id"`
	SessionID  string `json:"session_id"`
	Kind       string `json:"kind"`
	Content    string `json:"content"`
	TokenCount int64  `json:"token_count"`
	FileIds    string `json:"file_ids"`
}

func (q *Queries) LCMInsertSummary(ctx context.Context, arg LCMInsertSummaryParams) error {
	_, err := q.exec(ctx, q.lCMInsertSummaryStmt, lCMInsertSummary,
		arg.SummaryID,
		arg.SessionID,
		arg.Kind,
		arg.Content,
		arg.TokenCount,
		arg.FileIds,
	)
	return err
}

const lCMInsertSummaryMessage = `-- name: LCMInsertSummaryMessage :exec
INSERT INTO lcm_summary_messages (summary_id, message_id, ord) VALUES (?, ?, ?)
ON CONFLICT(summary_id, message_id) DO NOTHING
`

type LCMInsertSummaryMessageParams struct {
	SummaryID string `json:"summary_id"`
	MessageID string `json:"message_id"`
	Ord       int64  `json:"ord"`
}

func (q *Queries) LCMInsertSummaryMessage(ctx context.Context, arg LCMInsertSummaryMessageParams) error {
	_, err := q.exec(ctx, q.lCMInsertSummaryMessageStmt, lCMInsertSummaryMessage, arg.SummaryID, arg.MessageID, arg.Ord)
	return err
}

const lCMInsertSummaryParent = `-- name: LCMInsertSummaryParent :exec
INSERT INTO lcm_summary_parents (summary_id, parent_summary_id, ord) VALUES (?, ?, ?)
ON CONFLICT(summary_id, parent_summary_id) DO NOTHING
`

type LCMInsertSummaryParentParams struct {
	SummaryID       string `json:"summary_id"`
	ParentSummaryID string `json:"parent_summary_id"`
	Ord             int64  `json:"ord"`
}

func (q *Queries) LCMInsertSummaryParent(ctx context.Context, arg LCMInsertSummaryParentParams) error {
	_, err := q.exec(ctx, q.lCMInsertSummaryParentStmt, lCMInsertSummaryParent, arg.SummaryID, arg.ParentSummaryID, arg.Ord)
	return err
}
