// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lcm.sql

package db

import (
	"context"
	"database/sql"
)

const lCMAppendContextItem = `-- name: LCMAppendContextItem :exec
INSERT INTO lcm_context_items (session_id, position, item_type, message_id, summary_id)
SELECT ?, COALESCE(MAX(ci.position), -1) + 1, ?, ?, ?
FROM lcm_context_items ci
WHERE ci.session_id = ?5
`

type LCMAppendContextItemParams struct {
	SessionID string         `json:"session_id"`
	ItemType  string         `json:"item_type"`
	MessageID sql.NullString `json:"message_id"`
	SummaryID sql.NullString `json:"summary_id"`
}

func (q *Queries) LCMAppendContextItem(ctx context.Context, arg LCMAppendContextItemParams) error {
	_, err := q.exec(ctx, q.lCMAppendContextItemStmt, lCMAppendContextItem,
		arg.SessionID,
		arg.ItemType,
		arg.MessageID,
		arg.SummaryID,
		arg.SessionID,
	)
	return err
}

const lCMCountMessagesInContext = `-- name: LCMCountMessagesInContext :one
SELECT COUNT(*) FROM lcm_context_items
WHERE session_id = ? AND item_type = 'message'
`

func (q *Queries) LCMCountMessagesInContext(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.lCMCountMessagesInContextStmt, lCMCountMessagesInContext, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const lCMCountSummariesInContext = `-- name: LCMCountSummariesInContext :one
SELECT COUNT(*) FROM lcm_context_items
WHERE session_id = ? AND item_type = 'summary'
`

func (q *Queries) LCMCountSummariesInContext(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.lCMCountSummariesInContextStmt, lCMCountSummariesInContext, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const lCMExpandSummaryToMessages = `-- name: LCMExpandSummaryToMessages :many
SELECT m.id, m.session_id, m.role, m.parts AS content, m.created_at,
       COALESCE(m.token_count, (LENGTH(COALESCE(m.parts, '')) + 3) / 4) AS token_count
FROM lcm_summary_messages sm
JOIN messages m ON m.id = sm.message_id
WHERE sm.summary_id = ?
ORDER BY sm.ord
`

type LCMExpandSummaryToMessagesRow struct {
	ID         string `json:"id"`
	SessionID  string `json:"session_id"`
	Role       string `json:"role"`
	Content    string `json:"content"`
	CreatedAt  int64  `json:"created_at"`
	TokenCount int64  `json:"token_count"`
}

func (q *Queries) LCMExpandSummaryToMessages(ctx context.Context, summaryID string) ([]LCMExpandSummaryToMessagesRow, error) {
	rows, err := q.query(ctx, q.lCMExpandSummaryToMessagesStmt, lCMExpandSummaryToMessages, summaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LCMExpandSummaryToMessagesRow{}
	for rows.Next() {
		var i LCMExpandSummaryToMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.TokenCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lCMGetContextTokenCount = `-- name: LCMGetContextTokenCount :one
SELECT COALESCE(SUM(
    CASE
        WHEN ci.item_type = 'message' THEN COALESCE(m.token_count, (LENGTH(COALESCE(m.parts, '')) + 3) / 4)
        WHEN ci.item_type = 'summary' THEN s.token_count
        ELSE 0
    END
), 0) AS total_tokens
FROM lcm_context_items ci
LEFT JOIN messages m ON m.id = ci.message_id
LEFT JOIN lcm_summaries s ON s.summary_id = ci.summary_id
WHERE ci.session_id = ?
`

func (q *Queries) LCMGetContextTokenCount(ctx context.Context, sessionID string) (interface{}, error) {
	row := q.queryRow(ctx, q.lCMGetContextTokenCountStmt, lCMGetContextTokenCount, sessionID)
	var total_tokens interface{}
	err := row.Scan(&total_tokens)
	return total_tokens, err
}

const lCMGetCurrentContext = `-- name: LCMGetCurrentContext :many
SELECT
    ci.position,
    ci.item_type,
    ci.message_id,
    ci.summary_id,
    COALESCE(m.role, 'summary') AS role,
    COALESCE(m.parts, s.content) AS content,
    CASE
        WHEN ci.item_type = 'message' THEN COALESCE(m.token_count, (LENGTH(COALESCE(m.parts, '')) + 3) / 4)
        ELSE COALESCE(s.token_count, 0)
    END AS token_count,
    COALESCE(s.kind, '') AS summary_kind
FROM lcm_context_items ci
LEFT JOIN messages m ON m.id = ci.message_id
LEFT JOIN lcm_summaries s ON s.summary_id = ci.summary_id
WHERE ci.session_id = ?
ORDER BY ci.position
`

type LCMGetCurrentContextRow struct {
	Position    int64          `json:"position"`
	ItemType    string         `json:"item_type"`
	MessageID   sql.NullString `json:"message_id"`
	SummaryID   sql.NullString `json:"summary_id"`
	Role        string         `json:"role"`
	Content     string         `json:"content"`
	TokenCount  interface{}    `json:"token_count"`
	SummaryKind string         `json:"summary_kind"`
}

func (q *Queries) LCMGetCurrentContext(ctx context.Context, sessionID string) ([]LCMGetCurrentContextRow, error) {
	rows, err := q.query(ctx, q.lCMGetCurrentContextStmt, lCMGetCurrentContext, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LCMGetCurrentContextRow{}
	for rows.Next() {
		var i LCMGetCurrentContextRow
		if err := rows.Scan(
			&i.Position,
			&i.ItemType,
			&i.MessageID,
			&i.SummaryID,
			&i.Role,
			&i.Content,
			&i.TokenCount,
			&i.SummaryKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lCMGetLargeFile = `-- name: LCMGetLargeFile :one
SELECT file_id, session_id, original_path, mime_type, token_count, created_at,
       exploration_summary, explorer_used
FROM lcm_large_files WHERE file_id = ?
`

func (q *Queries) LCMGetLargeFile(ctx context.Context, fileID string) (LcmLargeFile, error) {
	row := q.queryRow(ctx, q.lCMGetLargeFileStmt, lCMGetLargeFile, fileID)
	var i LcmLargeFile
	err := row.Scan(
		&i.FileID,
		&i.SessionID,
		&i.OriginalPath,
		&i.MimeType,
		&i.TokenCount,
		&i.CreatedAt,
		&i.ExplorationSummary,
		&i.ExplorerUsed,
	)
	return i, err
}

const lCMGetMessageByID = `-- name: LCMGetMessageByID :one
SELECT m.id, m.session_id, m.role, m.parts AS content, m.created_at,
       COALESCE(m.token_count, (LENGTH(COALESCE(m.parts, '')) + 3) / 4) AS token_count
FROM messages m
WHERE m.id = ?
`

type LCMGetMessageByIDRow struct {
	ID         string `json:"id"`
	SessionID  string `json:"session_id"`
	Role       string `json:"role"`
	Content    string `json:"content"`
	CreatedAt  int64  `json:"created_at"`
	TokenCount int64  `json:"token_count"`
}

func (q *Queries) LCMGetMessageByID(ctx context.Context, id string) (LCMGetMessageByIDRow, error) {
	row := q.queryRow(ctx, q.lCMGetMessageByIDStmt, lCMGetMessageByID, id)
	var i LCMGetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.TokenCount,
	)
	return i, err
}

const lCMGetMessagesToSummarize = `-- name: LCMGetMessagesToSummarize :many
SELECT ci.position, ci.item_type, ci.message_id, ci.summary_id
FROM lcm_context_items ci
WHERE ci.session_id = ? AND ci.item_type = 'message'
ORDER BY ci.position
LIMIT ?
`

type LCMGetMessagesToSummarizeParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

type LCMGetMessagesToSummarizeRow struct {
	Position  int64          `json:"position"`
	ItemType  string         `json:"item_type"`
	MessageID sql.NullString `json:"message_id"`
	SummaryID sql.NullString `json:"summary_id"`
}

func (q *Queries) LCMGetMessagesToSummarize(ctx context.Context, arg LCMGetMessagesToSummarizeParams) ([]LCMGetMessagesToSummarizeRow, error) {
	rows, err := q.query(ctx, q.lCMGetMessagesToSummarizeStmt, lCMGetMessagesToSummarize, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LCMGetMessagesToSummarizeRow{}
	for rows.Next() {
		var i LCMGetMessagesToSummarizeRow
		if err := rows.Scan(
			&i.Position,
			&i.ItemType,
			&i.MessageID,
			&i.SummaryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// --- Phase 3.2: Token-budget windowed selection ---

const lCMGetMessagesToSummarizeByTokenBudget = `-- name: LCMGetMessagesToSummarizeByTokenBudget :many
SELECT sub.position, sub.item_type, sub.message_id, sub.summary_id
FROM (
    SELECT ci.position, ci.item_type, ci.message_id, ci.summary_id,
           SUM(COALESCE(m.token_count, (LENGTH(COALESCE(m.parts, '')) + 3) / 4))
               OVER (ORDER BY ci.position) AS running_tokens
    FROM lcm_context_items ci
    LEFT JOIN messages m ON m.id = ci.message_id
    WHERE ci.session_id = ? AND ci.item_type = 'message'
) sub
WHERE sub.running_tokens <= ?
`

type LCMGetMessagesToSummarizeByTokenBudgetParams struct {
	SessionID   string `json:"session_id"`
	TokenBudget int64  `json:"token_budget"`
}

type LCMGetMessagesToSummarizeByTokenBudgetRow struct {
	Position  int64          `json:"position"`
	ItemType  string         `json:"item_type"`
	MessageID sql.NullString `json:"message_id"`
	SummaryID sql.NullString `json:"summary_id"`
}

func (q *Queries) LCMGetMessagesToSummarizeByTokenBudget(ctx context.Context, arg LCMGetMessagesToSummarizeByTokenBudgetParams) ([]LCMGetMessagesToSummarizeByTokenBudgetRow, error) {
	rows, err := q.query(ctx, q.lCMGetMessagesToSummarizeByTokenBudgetStmt, lCMGetMessagesToSummarizeByTokenBudget, arg.SessionID, arg.TokenBudget)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LCMGetMessagesToSummarizeByTokenBudgetRow{}
	for rows.Next() {
		var i LCMGetMessagesToSummarizeByTokenBudgetRow
		if err := rows.Scan(
			&i.Position,
			&i.ItemType,
			&i.MessageID,
			&i.SummaryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// --- Exploration cache queries (Phase 5.2) ---

const lCMUpdateLargeFileExploration = `-- name: LCMUpdateLargeFileExploration :exec
UPDATE lcm_large_files
SET exploration_summary = ?, explorer_used = ?
WHERE file_id = ?
`

type LCMUpdateLargeFileExplorationParams struct {
	ExplorationSummary sql.NullString `json:"exploration_summary"`
	ExplorerUsed       sql.NullString `json:"explorer_used"`
	FileID             string         `json:"file_id"`
}

func (q *Queries) LCMUpdateLargeFileExploration(ctx context.Context, arg LCMUpdateLargeFileExplorationParams) error {
	_, err := q.exec(ctx, q.lCMUpdateLargeFileExplorationStmt, lCMUpdateLargeFileExploration,
		arg.ExplorationSummary,
		arg.ExplorerUsed,
		arg.FileID,
	)
	return err
}

const lCMGetLargeFileExploration = `-- name: LCMGetLargeFileExploration :one
SELECT exploration_summary, explorer_used
FROM lcm_large_files WHERE file_id = ?
`

type LCMGetLargeFileExplorationRow struct {
	ExplorationSummary sql.NullString `json:"exploration_summary"`
	ExplorerUsed       sql.NullString `json:"explorer_used"`
}

func (q *Queries) LCMGetLargeFileExploration(ctx context.Context, fileID string) (LCMGetLargeFileExplorationRow, error) {
	row := q.queryRow(ctx, q.lCMGetLargeFileExplorationStmt, lCMGetLargeFileExploration, fileID)
	var i LCMGetLargeFileExplorationRow
	err := row.Scan(&i.ExplorationSummary, &i.ExplorerUsed)
	return i, err
}

const lCMGetOldestSummariesInContext = `-- name: LCMGetOldestSummariesInContext :many
SELECT ci.position, ci.item_type, ci.message_id, ci.summary_id
FROM lcm_context_items ci
WHERE ci.session_id = ? AND ci.item_type = 'summary'
ORDER BY ci.position
LIMIT ?
`

type LCMGetOldestSummariesInContextParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

type LCMGetOldestSummariesInContextRow struct {
	Position  int64          `json:"position"`
	ItemType  string         `json:"item_type"`
	MessageID sql.NullString `json:"message_id"`
	SummaryID sql.NullString `json:"summary_id"`
}

func (q *Queries) LCMGetOldestSummariesInContext(ctx context.Context, arg LCMGetOldestSummariesInContextParams) ([]LCMGetOldestSummariesInContextRow, error) {
	rows, err := q.query(ctx, q.lCMGetOldestSummariesInContextStmt, lCMGetOldestSummariesInContext, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LCMGetOldestSummariesInContextRow{}
	for rows.Next() {
		var i LCMGetOldestSummariesInContextRow
		if err := rows.Scan(
			&i.Position,
			&i.ItemType,
			&i.MessageID,
			&i.SummaryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lCMGetSummaryByID = `-- name: LCMGetSummaryByID :one
SELECT summary_id, session_id, kind, content, token_count, file_ids, created_at
FROM lcm_summaries WHERE summary_id = ?
`

type LCMGetSummaryByIDRow struct {
	SummaryID  string `json:"summary_id"`
	SessionID  string `json:"session_id"`
	Kind       string `json:"kind"`
	Content    string `json:"content"`
	TokenCount int64  `json:"token_count"`
	FileIds    string `json:"file_ids"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) LCMGetSummaryByID(ctx context.Context, summaryID string) (LCMGetSummaryByIDRow, error) {
	row := q.queryRow(ctx, q.lCMGetSummaryByIDStmt, lCMGetSummaryByID, summaryID)
	var i LCMGetSummaryByIDRow
	err := row.Scan(
		&i.SummaryID,
		&i.SessionID,
		&i.Kind,
		&i.Content,
		&i.TokenCount,
		&i.FileIds,
		&i.CreatedAt,
	)
	return i, err
}

const lCMGetSummaryParentIDs = `-- name: LCMGetSummaryParentIDs :many
SELECT parent_summary_id FROM lcm_summary_parents
WHERE summary_id = ? ORDER BY ord
`

func (q *Queries) LCMGetSummaryParentIDs(ctx context.Context, summaryID string) ([]string, error) {
	rows, err := q.query(ctx, q.lCMGetSummaryParentIDsStmt, lCMGetSummaryParentIDs, summaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var parent_summary_id string
		if err := rows.Scan(&parent_summary_id); err != nil {
			return nil, err
		}
		items = append(items, parent_summary_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lCMInsertLargeFile = `-- name: LCMInsertLargeFile :exec

INSERT INTO lcm_large_files (file_id, session_id, original_path, mime_type, token_count)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(file_id) DO NOTHING
`

type LCMInsertLargeFileParams struct {
	FileID       string `json:"file_id"`
	SessionID    string `json:"session_id"`
	OriginalPath string `json:"original_path"`
	MimeType     string `json:"mime_type"`
	TokenCount   int64  `json:"token_count"`
}

// FTS5 search query is implemented directly in the SQLiteStore
// because sqlc cannot introspect FTS5 virtual tables.
func (q *Queries) LCMInsertLargeFile(ctx context.Context, arg LCMInsertLargeFileParams) error {
	_, err := q.exec(ctx, q.lCMInsertLargeFileStmt, lCMInsertLargeFile,
		arg.FileID,
		arg.SessionID,
		arg.OriginalPath,
		arg.MimeType,
		arg.TokenCount,
	)
	return err
}

const lCMInsertSummary = `-- name: LCMInsertSummary :exec
INSERT INTO lcm_summaries (summary_id, session_id, kind, content, token_count, file_ids)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(summary_id) DO NOTHING
`

type LCMInsertSummaryParams struct {
	SummaryID  string `json:"summary_id"`
	SessionID  string `json:"session_id"`
	Kind       string `json:"kind"`
	Content    string `json:"content"`
	TokenCount int64  `json:"token_count"`
	FileIds    string `json:"file_ids"`
}

func (q *Queries) LCMInsertSummary(ctx context.Context, arg LCMInsertSummaryParams) error {
	_, err := q.exec(ctx, q.lCMInsertSummaryStmt, lCMInsertSummary,
		arg.SummaryID,
		arg.SessionID,
		arg.Kind,
		arg.Content,
		arg.TokenCount,
		arg.FileIds,
	)
	return err
}

const lCMInsertSummaryMessage = `-- name: LCMInsertSummaryMessage :exec
INSERT INTO lcm_summary_messages (summary_id, message_id, ord) VALUES (?, ?, ?)
ON CONFLICT(summary_id, message_id) DO NOTHING
`

type LCMInsertSummaryMessageParams struct {
	SummaryID string `json:"summary_id"`
	MessageID string `json:"message_id"`
	Ord       int64  `json:"ord"`
}

func (q *Queries) LCMInsertSummaryMessage(ctx context.Context, arg LCMInsertSummaryMessageParams) error {
	_, err := q.exec(ctx, q.lCMInsertSummaryMessageStmt, lCMInsertSummaryMessage, arg.SummaryID, arg.MessageID, arg.Ord)
	return err
}

const lCMInsertSummaryParent = `-- name: LCMInsertSummaryParent :exec
INSERT INTO lcm_summary_parents (summary_id, parent_summary_id, ord) VALUES (?, ?, ?)
ON CONFLICT(summary_id, parent_summary_id) DO NOTHING
`

type LCMInsertSummaryParentParams struct {
	SummaryID       string `json:"summary_id"`
	ParentSummaryID string `json:"parent_summary_id"`
	Ord             int64  `json:"ord"`
}

func (q *Queries) LCMInsertSummaryParent(ctx context.Context, arg LCMInsertSummaryParentParams) error {
	_, err := q.exec(ctx, q.lCMInsertSummaryParentStmt, lCMInsertSummaryParent, arg.SummaryID, arg.ParentSummaryID, arg.Ord)
	return err
}

// --- DB-26: LCMGetChildSummaryIDs ---

const lCMGetChildSummaryIDs = `-- name: LCMGetChildSummaryIDs :many
SELECT summary_id FROM lcm_summary_parents
WHERE parent_summary_id = ? ORDER BY ord
`

func (q *Queries) LCMGetChildSummaryIDs(ctx context.Context, parentSummaryID string) ([]string, error) {
	rows, err := q.query(ctx, q.lCMGetChildSummaryIDsStmt, lCMGetChildSummaryIDs, parentSummaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var summaryID string
		if err := rows.Scan(&summaryID); err != nil {
			return nil, err
		}
		items = append(items, summaryID)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// --- DB-25: LCMGetCoveringSummaryForMessages ---

const lCMGetCoveringSummaryForMessages = `-- name: LCMGetCoveringSummaryForMessages :one
SELECT s.summary_id, s.session_id, s.kind, s.content, s.token_count, s.file_ids, s.created_at
FROM lcm_summaries s
WHERE s.session_id = ?
  AND s.kind = 'leaf'
  AND (
    SELECT COUNT(DISTINCT sm.message_id)
    FROM lcm_summary_messages sm
    WHERE sm.summary_id = s.summary_id
  ) >= ?
ORDER BY s.created_at DESC
LIMIT 1
`

type LCMGetCoveringSummaryForMessagesParams struct {
	SessionID   string `json:"session_id"`
	MinMessages int64  `json:"min_messages"`
}

func (q *Queries) LCMGetCoveringSummaryForMessages(ctx context.Context, arg LCMGetCoveringSummaryForMessagesParams) (LCMGetSummaryByIDRow, error) {
	row := q.queryRow(ctx, q.lCMGetCoveringSummaryForMessagesStmt, lCMGetCoveringSummaryForMessages, arg.SessionID, arg.MinMessages)
	var i LCMGetSummaryByIDRow
	err := row.Scan(
		&i.SummaryID,
		&i.SessionID,
		&i.Kind,
		&i.Content,
		&i.TokenCount,
		&i.FileIds,
		&i.CreatedAt,
	)
	return i, err
}

// --- SQ-2: LCMGetAllSummaries ---

const lCMGetAllSummaries = `-- name: LCMGetAllSummaries :many
SELECT summary_id, session_id, kind, content, token_count, file_ids, created_at
FROM lcm_summaries
WHERE session_id = ?
ORDER BY created_at
`

func (q *Queries) LCMGetAllSummaries(ctx context.Context, sessionID string) ([]LCMGetSummaryByIDRow, error) {
	rows, err := q.query(ctx, q.lCMGetAllSummariesStmt, lCMGetAllSummaries, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LCMGetSummaryByIDRow{}
	for rows.Next() {
		var i LCMGetSummaryByIDRow
		if err := rows.Scan(
			&i.SummaryID,
			&i.SessionID,
			&i.Kind,
			&i.Content,
			&i.TokenCount,
			&i.FileIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// --- SQ-2: LCMDeleteSummary ---

const lCMDeleteSummary = `-- name: LCMDeleteSummary :exec
DELETE FROM lcm_summaries WHERE summary_id = ?
`

func (q *Queries) LCMDeleteSummary(ctx context.Context, summaryID string) error {
	_, err := q.exec(ctx, q.lCMDeleteSummaryStmt, lCMDeleteSummary, summaryID)
	return err
}

// --- DB-15/DB-16: LCMGetSessionConfig ---

const lCMGetSessionConfig = `-- name: LCMGetSessionConfig :one
SELECT session_id, model_name, model_ctx_max_tokens, ctx_cutoff_threshold, created_at, updated_at
FROM lcm_session_config WHERE session_id = ?
`

type LcmSessionConfig struct {
	SessionID          string        `json:"session_id"`
	ModelName          string        `json:"model_name"`
	ModelCtxMaxTokens  int64         `json:"model_ctx_max_tokens"`
	CtxCutoffThreshold sql.NullInt64 `json:"ctx_cutoff_threshold"`
	CreatedAt          int64         `json:"created_at"`
	UpdatedAt          int64         `json:"updated_at"`
}

func (q *Queries) LCMGetSessionConfig(ctx context.Context, sessionID string) (LcmSessionConfig, error) {
	row := q.queryRow(ctx, q.lCMGetSessionConfigStmt, lCMGetSessionConfig, sessionID)
	var i LcmSessionConfig
	err := row.Scan(
		&i.SessionID,
		&i.ModelName,
		&i.ModelCtxMaxTokens,
		&i.CtxCutoffThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// --- DB-15/DB-16: LCMUpsertSessionConfig ---

const lCMUpsertSessionConfig = `-- name: LCMUpsertSessionConfig :exec
INSERT INTO lcm_session_config (session_id, model_name, model_ctx_max_tokens, ctx_cutoff_threshold)
VALUES (?, ?, ?, ?)
ON CONFLICT(session_id) DO UPDATE SET
    model_name = excluded.model_name,
    model_ctx_max_tokens = excluded.model_ctx_max_tokens,
    ctx_cutoff_threshold = excluded.ctx_cutoff_threshold,
    updated_at = strftime('%s','now')
`

type LCMUpsertSessionConfigParams struct {
	SessionID          string        `json:"session_id"`
	ModelName          string        `json:"model_name"`
	ModelCtxMaxTokens  int64         `json:"model_ctx_max_tokens"`
	CtxCutoffThreshold sql.NullInt64 `json:"ctx_cutoff_threshold"`
}

func (q *Queries) LCMUpsertSessionConfig(ctx context.Context, arg LCMUpsertSessionConfigParams) error {
	_, err := q.exec(ctx, q.lCMUpsertSessionConfigStmt, lCMUpsertSessionConfig,
		arg.SessionID,
		arg.ModelName,
		arg.ModelCtxMaxTokens,
		arg.CtxCutoffThreshold,
	)
	return err
}

// --- DB-27: LCMGetSummaryMessageSessionIDs ---

const lCMGetSummaryMessageSessionIDs = `-- name: LCMGetSummaryMessageSessionIDs :many
SELECT DISTINCT m.session_id
FROM lcm_summary_messages sm
JOIN messages m ON m.id = sm.message_id
WHERE sm.summary_id = ?
`

func (q *Queries) LCMGetSummaryMessageSessionIDs(ctx context.Context, summaryID string) ([]string, error) {
	rows, err := q.query(ctx, q.lCMGetSummaryMessageSessionIDsStmt, lCMGetSummaryMessageSessionIDs, summaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var sessionID string
		if err := rows.Scan(&sessionID); err != nil {
			return nil, err
		}
		items = append(items, sessionID)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
