// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: map.sql

package db

import (
	"context"
	"database/sql"
)

// ---------------------------------------------------------------------------
// Agentic Map Runs
// ---------------------------------------------------------------------------

const createAgenticMapRun = `-- name: CreateAgenticMapRun :exec
INSERT INTO agentic_map_runs (
    map_id, run_started_at, status, input_path, input_lcm_id,
    output_path, output_lcm_id, prompt, output_schema,
    read_only, concurrency, timeout_seconds, max_attempts
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAgenticMapRunParams struct {
	MapID          string         `json:"map_id"`
	RunStartedAt   int64          `json:"run_started_at"`
	Status         string         `json:"status"`
	InputPath      sql.NullString `json:"input_path"`
	InputLcmID     sql.NullString `json:"input_lcm_id"`
	OutputPath     sql.NullString `json:"output_path"`
	OutputLcmID    sql.NullString `json:"output_lcm_id"`
	Prompt         sql.NullString `json:"prompt"`
	OutputSchema   sql.NullString `json:"output_schema"`
	ReadOnly       int64          `json:"read_only"`
	Concurrency    int64          `json:"concurrency"`
	TimeoutSeconds int64          `json:"timeout_seconds"`
	MaxAttempts    int64          `json:"max_attempts"`
}

func (q *Queries) CreateAgenticMapRun(ctx context.Context, arg CreateAgenticMapRunParams) error {
	_, err := q.exec(ctx, q.createAgenticMapRunStmt, createAgenticMapRun,
		arg.MapID, arg.RunStartedAt, arg.Status, arg.InputPath, arg.InputLcmID,
		arg.OutputPath, arg.OutputLcmID, arg.Prompt, arg.OutputSchema,
		arg.ReadOnly, arg.Concurrency, arg.TimeoutSeconds, arg.MaxAttempts,
	)
	return err
}

const getAgenticMapRun = `-- name: GetAgenticMapRun :one
SELECT map_id, run_started_at, status, input_path, input_lcm_id,
       output_path, output_lcm_id, prompt, output_schema,
       read_only, concurrency, timeout_seconds, max_attempts
FROM agentic_map_runs WHERE map_id = ?
`

func (q *Queries) GetAgenticMapRun(ctx context.Context, mapID string) (AgenticMapRun, error) {
	row := q.queryRow(ctx, q.getAgenticMapRunStmt, getAgenticMapRun, mapID)
	var i AgenticMapRun
	err := row.Scan(
		&i.MapID, &i.RunStartedAt, &i.Status, &i.InputPath, &i.InputLcmID,
		&i.OutputPath, &i.OutputLcmID, &i.Prompt, &i.OutputSchema,
		&i.ReadOnly, &i.Concurrency, &i.TimeoutSeconds, &i.MaxAttempts,
	)
	return i, err
}

const updateAgenticMapRunStatus = `-- name: UpdateAgenticMapRunStatus :exec
UPDATE agentic_map_runs SET status = ? WHERE map_id = ?
`

type UpdateAgenticMapRunStatusParams struct {
	Status string `json:"status"`
	MapID  string `json:"map_id"`
}

func (q *Queries) UpdateAgenticMapRunStatus(ctx context.Context, arg UpdateAgenticMapRunStatusParams) error {
	_, err := q.exec(ctx, q.updateAgenticMapRunStatusStmt, updateAgenticMapRunStatus, arg.Status, arg.MapID)
	return err
}

// ---------------------------------------------------------------------------
// Agentic Map Items
// ---------------------------------------------------------------------------

const createAgenticMapItem = `-- name: CreateAgenticMapItem :exec
INSERT INTO agentic_map_items (
    map_id, item_index, item, status, attempts_used,
    started_at, finished_at, result, error
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAgenticMapItemParams struct {
	MapID        string         `json:"map_id"`
	ItemIndex    int64          `json:"item_index"`
	Item         string         `json:"item"`
	Status       string         `json:"status"`
	AttemptsUsed int64          `json:"attempts_used"`
	StartedAt    sql.NullInt64  `json:"started_at"`
	FinishedAt   sql.NullInt64  `json:"finished_at"`
	Result       sql.NullString `json:"result"`
	Error        sql.NullString `json:"error"`
}

func (q *Queries) CreateAgenticMapItem(ctx context.Context, arg CreateAgenticMapItemParams) error {
	_, err := q.exec(ctx, q.createAgenticMapItemStmt, createAgenticMapItem,
		arg.MapID, arg.ItemIndex, arg.Item, arg.Status, arg.AttemptsUsed,
		arg.StartedAt, arg.FinishedAt, arg.Result, arg.Error,
	)
	return err
}

const getAgenticMapItem = `-- name: GetAgenticMapItem :one
SELECT map_id, item_index, item, status, attempts_used,
       started_at, finished_at, result, error
FROM agentic_map_items WHERE map_id = ? AND item_index = ?
`

type GetAgenticMapItemParams struct {
	MapID     string `json:"map_id"`
	ItemIndex int64  `json:"item_index"`
}

func (q *Queries) GetAgenticMapItem(ctx context.Context, arg GetAgenticMapItemParams) (AgenticMapItem, error) {
	row := q.queryRow(ctx, q.getAgenticMapItemStmt, getAgenticMapItem, arg.MapID, arg.ItemIndex)
	var i AgenticMapItem
	err := row.Scan(
		&i.MapID, &i.ItemIndex, &i.Item, &i.Status, &i.AttemptsUsed,
		&i.StartedAt, &i.FinishedAt, &i.Result, &i.Error,
	)
	return i, err
}

const updateAgenticMapItem = `-- name: UpdateAgenticMapItem :exec
UPDATE agentic_map_items
SET status = ?, attempts_used = ?, started_at = ?, finished_at = ?, result = ?, error = ?
WHERE map_id = ? AND item_index = ?
`

type UpdateAgenticMapItemParams struct {
	Status       string         `json:"status"`
	AttemptsUsed int64          `json:"attempts_used"`
	StartedAt    sql.NullInt64  `json:"started_at"`
	FinishedAt   sql.NullInt64  `json:"finished_at"`
	Result       sql.NullString `json:"result"`
	Error        sql.NullString `json:"error"`
	MapID        string         `json:"map_id"`
	ItemIndex    int64          `json:"item_index"`
}

func (q *Queries) UpdateAgenticMapItem(ctx context.Context, arg UpdateAgenticMapItemParams) error {
	_, err := q.exec(ctx, q.updateAgenticMapItemStmt, updateAgenticMapItem,
		arg.Status, arg.AttemptsUsed, arg.StartedAt, arg.FinishedAt, arg.Result, arg.Error,
		arg.MapID, arg.ItemIndex,
	)
	return err
}

const getAgenticMapItemsByStatus = `-- name: GetAgenticMapItemsByStatus :many
SELECT map_id, item_index, item, status, attempts_used,
       started_at, finished_at, result, error
FROM agentic_map_items WHERE map_id = ? AND status = ?
ORDER BY item_index
`

type GetAgenticMapItemsByStatusParams struct {
	MapID  string `json:"map_id"`
	Status string `json:"status"`
}

func (q *Queries) GetAgenticMapItemsByStatus(ctx context.Context, arg GetAgenticMapItemsByStatusParams) ([]AgenticMapItem, error) {
	rows, err := q.query(ctx, q.getAgenticMapItemsByStatusStmt, getAgenticMapItemsByStatus, arg.MapID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgenticMapItem{}
	for rows.Next() {
		var i AgenticMapItem
		if err := rows.Scan(
			&i.MapID, &i.ItemIndex, &i.Item, &i.Status, &i.AttemptsUsed,
			&i.StartedAt, &i.FinishedAt, &i.Result, &i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ---------------------------------------------------------------------------
// LLM Map Runs
// ---------------------------------------------------------------------------

const createLlmMapRun = `-- name: CreateLlmMapRun :exec
INSERT INTO llm_map_runs (
    map_id, run_started_at, status, input_path, input_lcm_id,
    output_path, output_lcm_id, prompt, output_schema, model,
    concurrency, timeout_seconds, max_attempts,
    resolved_provider, resolved_model, resolved_request_overrides
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateLlmMapRunParams struct {
	MapID                    string         `json:"map_id"`
	RunStartedAt             int64          `json:"run_started_at"`
	Status                   string         `json:"status"`
	InputPath                sql.NullString `json:"input_path"`
	InputLcmID               sql.NullString `json:"input_lcm_id"`
	OutputPath               sql.NullString `json:"output_path"`
	OutputLcmID              sql.NullString `json:"output_lcm_id"`
	Prompt                   sql.NullString `json:"prompt"`
	OutputSchema             sql.NullString `json:"output_schema"`
	Model                    sql.NullString `json:"model"`
	Concurrency              int64          `json:"concurrency"`
	TimeoutSeconds           int64          `json:"timeout_seconds"`
	MaxAttempts              int64          `json:"max_attempts"`
	ResolvedProvider         sql.NullString `json:"resolved_provider"`
	ResolvedModel            sql.NullString `json:"resolved_model"`
	ResolvedRequestOverrides sql.NullString `json:"resolved_request_overrides"`
}

func (q *Queries) CreateLlmMapRun(ctx context.Context, arg CreateLlmMapRunParams) error {
	_, err := q.exec(ctx, q.createLlmMapRunStmt, createLlmMapRun,
		arg.MapID, arg.RunStartedAt, arg.Status, arg.InputPath, arg.InputLcmID,
		arg.OutputPath, arg.OutputLcmID, arg.Prompt, arg.OutputSchema, arg.Model,
		arg.Concurrency, arg.TimeoutSeconds, arg.MaxAttempts,
		arg.ResolvedProvider, arg.ResolvedModel, arg.ResolvedRequestOverrides,
	)
	return err
}

const getLlmMapRun = `-- name: GetLlmMapRun :one
SELECT map_id, run_started_at, status, input_path, input_lcm_id,
       output_path, output_lcm_id, prompt, output_schema, model,
       concurrency, timeout_seconds, max_attempts,
       resolved_provider, resolved_model, resolved_request_overrides
FROM llm_map_runs WHERE map_id = ?
`

func (q *Queries) GetLlmMapRun(ctx context.Context, mapID string) (LlmMapRun, error) {
	row := q.queryRow(ctx, q.getLlmMapRunStmt, getLlmMapRun, mapID)
	var i LlmMapRun
	err := row.Scan(
		&i.MapID, &i.RunStartedAt, &i.Status, &i.InputPath, &i.InputLcmID,
		&i.OutputPath, &i.OutputLcmID, &i.Prompt, &i.OutputSchema, &i.Model,
		&i.Concurrency, &i.TimeoutSeconds, &i.MaxAttempts,
		&i.ResolvedProvider, &i.ResolvedModel, &i.ResolvedRequestOverrides,
	)
	return i, err
}

const updateLlmMapRunStatus = `-- name: UpdateLlmMapRunStatus :exec
UPDATE llm_map_runs SET status = ? WHERE map_id = ?
`

type UpdateLlmMapRunStatusParams struct {
	Status string `json:"status"`
	MapID  string `json:"map_id"`
}

func (q *Queries) UpdateLlmMapRunStatus(ctx context.Context, arg UpdateLlmMapRunStatusParams) error {
	_, err := q.exec(ctx, q.updateLlmMapRunStatusStmt, updateLlmMapRunStatus, arg.Status, arg.MapID)
	return err
}

// ---------------------------------------------------------------------------
// LLM Map Items
// ---------------------------------------------------------------------------

const createLlmMapItem = `-- name: CreateLlmMapItem :exec
INSERT INTO llm_map_items (
    map_id, item_index, item, status, attempts_used,
    started_at, finished_at, result, error
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateLlmMapItemParams struct {
	MapID        string         `json:"map_id"`
	ItemIndex    int64          `json:"item_index"`
	Item         string         `json:"item"`
	Status       string         `json:"status"`
	AttemptsUsed int64          `json:"attempts_used"`
	StartedAt    sql.NullInt64  `json:"started_at"`
	FinishedAt   sql.NullInt64  `json:"finished_at"`
	Result       sql.NullString `json:"result"`
	Error        sql.NullString `json:"error"`
}

func (q *Queries) CreateLlmMapItem(ctx context.Context, arg CreateLlmMapItemParams) error {
	_, err := q.exec(ctx, q.createLlmMapItemStmt, createLlmMapItem,
		arg.MapID, arg.ItemIndex, arg.Item, arg.Status, arg.AttemptsUsed,
		arg.StartedAt, arg.FinishedAt, arg.Result, arg.Error,
	)
	return err
}

const getLlmMapItem = `-- name: GetLlmMapItem :one
SELECT map_id, item_index, item, status, attempts_used,
       started_at, finished_at, result, error
FROM llm_map_items WHERE map_id = ? AND item_index = ?
`

type GetLlmMapItemParams struct {
	MapID     string `json:"map_id"`
	ItemIndex int64  `json:"item_index"`
}

func (q *Queries) GetLlmMapItem(ctx context.Context, arg GetLlmMapItemParams) (LlmMapItem, error) {
	row := q.queryRow(ctx, q.getLlmMapItemStmt, getLlmMapItem, arg.MapID, arg.ItemIndex)
	var i LlmMapItem
	err := row.Scan(
		&i.MapID, &i.ItemIndex, &i.Item, &i.Status, &i.AttemptsUsed,
		&i.StartedAt, &i.FinishedAt, &i.Result, &i.Error,
	)
	return i, err
}

const updateLlmMapItem = `-- name: UpdateLlmMapItem :exec
UPDATE llm_map_items
SET status = ?, attempts_used = ?, started_at = ?, finished_at = ?, result = ?, error = ?
WHERE map_id = ? AND item_index = ?
`

type UpdateLlmMapItemParams struct {
	Status       string         `json:"status"`
	AttemptsUsed int64          `json:"attempts_used"`
	StartedAt    sql.NullInt64  `json:"started_at"`
	FinishedAt   sql.NullInt64  `json:"finished_at"`
	Result       sql.NullString `json:"result"`
	Error        sql.NullString `json:"error"`
	MapID        string         `json:"map_id"`
	ItemIndex    int64          `json:"item_index"`
}

func (q *Queries) UpdateLlmMapItem(ctx context.Context, arg UpdateLlmMapItemParams) error {
	_, err := q.exec(ctx, q.updateLlmMapItemStmt, updateLlmMapItem,
		arg.Status, arg.AttemptsUsed, arg.StartedAt, arg.FinishedAt, arg.Result, arg.Error,
		arg.MapID, arg.ItemIndex,
	)
	return err
}

const getLlmMapItemsByStatus = `-- name: GetLlmMapItemsByStatus :many
SELECT map_id, item_index, item, status, attempts_used,
       started_at, finished_at, result, error
FROM llm_map_items WHERE map_id = ? AND status = ?
ORDER BY item_index
`

type GetLlmMapItemsByStatusParams struct {
	MapID  string `json:"map_id"`
	Status string `json:"status"`
}

func (q *Queries) GetLlmMapItemsByStatus(ctx context.Context, arg GetLlmMapItemsByStatusParams) ([]LlmMapItem, error) {
	rows, err := q.query(ctx, q.getLlmMapItemsByStatusStmt, getLlmMapItemsByStatus, arg.MapID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmMapItem{}
	for rows.Next() {
		var i LlmMapItem
		if err := rows.Scan(
			&i.MapID, &i.ItemIndex, &i.Item, &i.Status, &i.AttemptsUsed,
			&i.StartedAt, &i.FinishedAt, &i.Result, &i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
