// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message_parts.sql

package db

import (
	"context"
	"database/sql"
)

const insertMessagePart = `-- name: InsertMessagePart :exec
INSERT INTO message_parts (part_id, message_id, session_id, part_type, ordinal, text_content)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(part_id) DO NOTHING
`

type InsertMessagePartParams struct {
	PartID      string         `json:"part_id"`
	MessageID   string         `json:"message_id"`
	SessionID   string         `json:"session_id"`
	PartType    string         `json:"part_type"`
	Ordinal     int64          `json:"ordinal"`
	TextContent sql.NullString `json:"text_content"`
}

func (q *Queries) InsertMessagePart(ctx context.Context, arg InsertMessagePartParams) error {
	_, err := q.exec(ctx, q.insertMessagePartStmt, insertMessagePart,
		arg.PartID, arg.MessageID, arg.SessionID, arg.PartType, arg.Ordinal, arg.TextContent,
	)
	return err
}

const getMessagePartsByMessageID = `-- name: GetMessagePartsByMessageID :many
SELECT part_id, message_id, session_id, part_type, ordinal, text_content,
       is_ignored, is_synthetic, tool_call_id, tool_name, tool_status,
       tool_input, tool_output, tool_error, tool_title, patch_hash,
       patch_files, file_mime, file_name, file_url, subtask_prompt,
       subtask_desc, subtask_agent, step_reason, step_cost, step_tokens_in,
       step_tokens_out, snapshot_hash, compaction_auto, metadata
FROM message_parts WHERE message_id = ? ORDER BY ordinal
`

func (q *Queries) GetMessagePartsByMessageID(ctx context.Context, messageID string) ([]MessagePart, error) {
	rows, err := q.query(ctx, q.getMessagePartsByMessageIDStmt, getMessagePartsByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagePart{}
	for rows.Next() {
		var i MessagePart
		if err := rows.Scan(
			&i.PartID, &i.MessageID, &i.SessionID, &i.PartType, &i.Ordinal,
			&i.TextContent, &i.IsIgnored, &i.IsSynthetic, &i.ToolCallID,
			&i.ToolName, &i.ToolStatus, &i.ToolInput, &i.ToolOutput,
			&i.ToolError, &i.ToolTitle, &i.PatchHash, &i.PatchFiles,
			&i.FileMime, &i.FileName, &i.FileURL, &i.SubtaskPrompt,
			&i.SubtaskDesc, &i.SubtaskAgent, &i.StepReason, &i.StepCost,
			&i.StepTokensIn, &i.StepTokensOut, &i.SnapshotHash,
			&i.CompactionAuto, &i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagePartsByType = `-- name: GetMessagePartsByType :many
SELECT part_id, message_id, session_id, part_type, ordinal, text_content,
       is_ignored, is_synthetic, tool_call_id, tool_name, tool_status,
       tool_input, tool_output, tool_error, tool_title, patch_hash,
       patch_files, file_mime, file_name, file_url, subtask_prompt,
       subtask_desc, subtask_agent, step_reason, step_cost, step_tokens_in,
       step_tokens_out, snapshot_hash, compaction_auto, metadata
FROM message_parts WHERE session_id = ? AND part_type = ? ORDER BY ordinal
`

type GetMessagePartsByTypeParams struct {
	SessionID string `json:"session_id"`
	PartType  string `json:"part_type"`
}

func (q *Queries) GetMessagePartsByType(ctx context.Context, arg GetMessagePartsByTypeParams) ([]MessagePart, error) {
	rows, err := q.query(ctx, q.getMessagePartsByTypeStmt, getMessagePartsByType, arg.SessionID, arg.PartType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagePart{}
	for rows.Next() {
		var i MessagePart
		if err := rows.Scan(
			&i.PartID, &i.MessageID, &i.SessionID, &i.PartType, &i.Ordinal,
			&i.TextContent, &i.IsIgnored, &i.IsSynthetic, &i.ToolCallID,
			&i.ToolName, &i.ToolStatus, &i.ToolInput, &i.ToolOutput,
			&i.ToolError, &i.ToolTitle, &i.PatchHash, &i.PatchFiles,
			&i.FileMime, &i.FileName, &i.FileURL, &i.SubtaskPrompt,
			&i.SubtaskDesc, &i.SubtaskAgent, &i.StepReason, &i.StepCost,
			&i.StepTokensIn, &i.StepTokensOut, &i.SnapshotHash,
			&i.CompactionAuto, &i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMessagePartsByMessageID = `-- name: DeleteMessagePartsByMessageID :exec
DELETE FROM message_parts WHERE message_id = ?
`

func (q *Queries) DeleteMessagePartsByMessageID(ctx context.Context, messageID string) error {
	_, err := q.exec(ctx, q.deleteMessagePartsByMessageIDStmt, deleteMessagePartsByMessageID, messageID)
	return err
}
