// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type LcmContextItem struct {
	SessionID string         `json:"session_id"`
	Position  int64          `json:"position"`
	ItemType  string         `json:"item_type"`
	MessageID sql.NullString `json:"message_id"`
	SummaryID sql.NullString `json:"summary_id"`
}

type LcmLargeFile struct {
	FileID       string `json:"file_id"`
	SessionID    string `json:"session_id"`
	OriginalPath string `json:"original_path"`
	MimeType     string `json:"mime_type"`
	TokenCount   int64  `json:"token_count"`
	CreatedAt    int64  `json:"created_at"`
}

type LcmSummariesFt struct {
	Content string `json:"content"`
}

type MessagesFt struct {
	Parts string `json:"parts"`
}

type LcmSummary struct {
	SummaryID  string `json:"summary_id"`
	SessionID  string `json:"session_id"`
	Kind       string `json:"kind"`
	Content    string `json:"content"`
	TokenCount int64  `json:"token_count"`
	FileIds    string `json:"file_ids"`
	CreatedAt  int64  `json:"created_at"`
}

type LcmSummaryMessage struct {
	SummaryID string `json:"summary_id"`
	MessageID string `json:"message_id"`
	Ord       int64  `json:"ord"`
}

type LcmSummaryParent struct {
	SummaryID       string `json:"summary_id"`
	ParentSummaryID string `json:"parent_summary_id"`
	Ord             int64  `json:"ord"`
}

type Message struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	Role             string         `json:"role"`
	Parts            string         `json:"parts"`
	Model            sql.NullString `json:"model"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	FinishedAt       sql.NullInt64  `json:"finished_at"`
	Provider         sql.NullString `json:"provider"`
	IsSummaryMessage int64          `json:"is_summary_message"`
}

type ReadFile struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	ReadAt    int64  `json:"read_at"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	Todos            sql.NullString `json:"todos"`
}
