// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetAverageResponseTime(ctx context.Context) (int64, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetHourDayHeatmap(ctx context.Context) ([]GetHourDayHeatmapRow, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error)
	GetTotalStats(ctx context.Context) (GetTotalStatsRow, error)
	GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error)
	GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error)
	GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error)
	GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error)
	LCMAppendContextItem(ctx context.Context, arg LCMAppendContextItemParams) error
	LCMCountMessagesInContext(ctx context.Context, sessionID string) (int64, error)
	LCMCountSummariesInContext(ctx context.Context, sessionID string) (int64, error)
	LCMExpandSummaryToMessages(ctx context.Context, summaryID string) ([]LCMExpandSummaryToMessagesRow, error)
	LCMGetContextTokenCount(ctx context.Context, sessionID string) (interface{}, error)
	LCMGetCurrentContext(ctx context.Context, sessionID string) ([]LCMGetCurrentContextRow, error)
	LCMGetLargeFile(ctx context.Context, fileID string) (LcmLargeFile, error)
	LCMGetMessageByID(ctx context.Context, id string) (LCMGetMessageByIDRow, error)
	LCMGetMessagesToSummarize(ctx context.Context, arg LCMGetMessagesToSummarizeParams) ([]LCMGetMessagesToSummarizeRow, error)
	LCMGetOldestSummariesInContext(ctx context.Context, arg LCMGetOldestSummariesInContextParams) ([]LCMGetOldestSummariesInContextRow, error)
	LCMGetSummaryByID(ctx context.Context, summaryID string) (LCMGetSummaryByIDRow, error)
	LCMGetSummaryParentIDs(ctx context.Context, summaryID string) ([]string, error)
	// FTS5 search query is implemented directly in the SQLiteStore
	// because sqlc cannot introspect FTS5 virtual tables.
	LCMInsertLargeFile(ctx context.Context, arg LCMInsertLargeFileParams) error
	LCMInsertSummary(ctx context.Context, arg LCMInsertSummaryParams) error
	LCMInsertSummaryMessage(ctx context.Context, arg LCMInsertSummaryMessageParams) error
	LCMInsertSummaryParent(ctx context.Context, arg LCMInsertSummaryParentParams) error
	LCMGetChildSummaryIDs(ctx context.Context, parentSummaryID string) ([]string, error)
	LCMGetCoveringSummaryForMessages(ctx context.Context, arg LCMGetCoveringSummaryForMessagesParams) (LCMGetSummaryByIDRow, error)
	LCMGetAllSummaries(ctx context.Context, sessionID string) ([]LCMGetSummaryByIDRow, error)
	LCMDeleteSummary(ctx context.Context, summaryID string) error
	LCMGetSessionConfig(ctx context.Context, sessionID string) (LcmSessionConfig, error)
	LCMUpsertSessionConfig(ctx context.Context, arg LCMUpsertSessionConfigParams) error
	LCMGetSummaryMessageSessionIDs(ctx context.Context, summaryID string) ([]string, error)
	LCMGetMessagesToSummarizeByTokenBudget(ctx context.Context, arg LCMGetMessagesToSummarizeByTokenBudgetParams) ([]LCMGetMessagesToSummarizeByTokenBudgetRow, error)
	LCMUpdateLargeFileExploration(ctx context.Context, arg LCMUpdateLargeFileExplorationParams) error
	LCMGetLargeFileExploration(ctx context.Context, fileID string) (LCMGetLargeFileExplorationRow, error)
	InsertMessagePart(ctx context.Context, arg InsertMessagePartParams) error
	GetMessagePartsByMessageID(ctx context.Context, messageID string) ([]MessagePart, error)
	GetMessagePartsByType(ctx context.Context, arg GetMessagePartsByTypeParams) ([]MessagePart, error)
	DeleteMessagePartsByMessageID(ctx context.Context, messageID string) error
	CreateAgenticMapRun(ctx context.Context, arg CreateAgenticMapRunParams) error
	GetAgenticMapRun(ctx context.Context, mapID string) (AgenticMapRun, error)
	UpdateAgenticMapRunStatus(ctx context.Context, arg UpdateAgenticMapRunStatusParams) error
	CreateAgenticMapItem(ctx context.Context, arg CreateAgenticMapItemParams) error
	UpdateAgenticMapItem(ctx context.Context, arg UpdateAgenticMapItemParams) error
	GetAgenticMapItemsByStatus(ctx context.Context, arg GetAgenticMapItemsByStatusParams) ([]AgenticMapItem, error)
	CreateLlmMapRun(ctx context.Context, arg CreateLlmMapRunParams) error
	GetLlmMapRun(ctx context.Context, mapID string) (LlmMapRun, error)
	UpdateLlmMapRunStatus(ctx context.Context, arg UpdateLlmMapRunStatusParams) error
	CreateLlmMapItem(ctx context.Context, arg CreateLlmMapItemParams) error
	UpdateLlmMapItem(ctx context.Context, arg UpdateLlmMapItemParams) error
	GetLlmMapItemsByStatus(ctx context.Context, arg GetLlmMapItemsByStatusParams) ([]LlmMapItem, error)
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
}

var _ Querier = (*Queries)(nil)
